#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: namespace.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='namespace.proto',
  package='ai_flow',
  syntax='proto3',
  serialized_options=b'Z\010/ai_flow\220\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fnamespace.proto\x12\x07\x61i_flow\x1a\x1cgoogle/api/annotations.proto\x1a\x0c\x63ommon.proto\"\x8e\x01\n\x0eNamespaceProto\x12\x0c\n\x04name\x18\x02 \x01(\t\x12;\n\nproperties\x18\x03 \x03(\x0b\x32\'.ai_flow.NamespaceProto.PropertiesEntry\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"#\n\x13NamespaceIdentifier\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x9e\x01\n\x16UpdateNamespaceRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x43\n\nproperties\x18\x02 \x03(\x0b\x32/.ai_flow.UpdateNamespaceRequest.PropertiesEntry\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xe2\x03\n\x10NamespaceService\x12U\n\x0c\x61\x64\x64Namespace\x12\x17.ai_flow.NamespaceProto\x1a\x11.ai_flow.Response\"\x19\x82\xd3\xe4\x93\x02\x13\"\x0e/namespace/add:\x01*\x12^\n\x0cgetNamespace\x12\x1c.ai_flow.NamespaceIdentifier\x1a\x11.ai_flow.Response\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/namespace/get/{name}\x12\x63\n\x0fupdateNamespace\x12\x1f.ai_flow.UpdateNamespaceRequest\x1a\x11.ai_flow.Response\"\x1c\x82\xd3\xe4\x93\x02\x16\"\x11/namespace/update:\x01*\x12T\n\rlistNamespace\x12\x14.ai_flow.ListRequest\x1a\x11.ai_flow.Response\"\x1a\x82\xd3\xe4\x93\x02\x14\"\x0f/namespace/list:\x01*\x12\\\n\x0f\x64\x65leteNamespace\x12\x14.ai_flow.NameRequest\x1a\x11.ai_flow.Response\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/namespace/delete/{name}B\rZ\x08/ai_flow\x90\x01\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,common__pb2.DESCRIPTOR,])




_NAMESPACEPROTO_PROPERTIESENTRY = _descriptor.Descriptor(
  name='PropertiesEntry',
  full_name='ai_flow.NamespaceProto.PropertiesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ai_flow.NamespaceProto.PropertiesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='ai_flow.NamespaceProto.PropertiesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=215,
)

_NAMESPACEPROTO = _descriptor.Descriptor(
  name='NamespaceProto',
  full_name='ai_flow.NamespaceProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ai_flow.NamespaceProto.name', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='properties', full_name='ai_flow.NamespaceProto.properties', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_NAMESPACEPROTO_PROPERTIESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=215,
)


_NAMESPACEIDENTIFIER = _descriptor.Descriptor(
  name='NamespaceIdentifier',
  full_name='ai_flow.NamespaceIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ai_flow.NamespaceIdentifier.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=252,
)


_UPDATENAMESPACEREQUEST_PROPERTIESENTRY = _descriptor.Descriptor(
  name='PropertiesEntry',
  full_name='ai_flow.UpdateNamespaceRequest.PropertiesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ai_flow.UpdateNamespaceRequest.PropertiesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='ai_flow.UpdateNamespaceRequest.PropertiesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=215,
)

_UPDATENAMESPACEREQUEST = _descriptor.Descriptor(
  name='UpdateNamespaceRequest',
  full_name='ai_flow.UpdateNamespaceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ai_flow.UpdateNamespaceRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='properties', full_name='ai_flow.UpdateNamespaceRequest.properties', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_UPDATENAMESPACEREQUEST_PROPERTIESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=413,
)

_NAMESPACEPROTO_PROPERTIESENTRY.containing_type = _NAMESPACEPROTO
_NAMESPACEPROTO.fields_by_name['properties'].message_type = _NAMESPACEPROTO_PROPERTIESENTRY
_UPDATENAMESPACEREQUEST_PROPERTIESENTRY.containing_type = _UPDATENAMESPACEREQUEST
_UPDATENAMESPACEREQUEST.fields_by_name['properties'].message_type = _UPDATENAMESPACEREQUEST_PROPERTIESENTRY
DESCRIPTOR.message_types_by_name['NamespaceProto'] = _NAMESPACEPROTO
DESCRIPTOR.message_types_by_name['NamespaceIdentifier'] = _NAMESPACEIDENTIFIER
DESCRIPTOR.message_types_by_name['UpdateNamespaceRequest'] = _UPDATENAMESPACEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NamespaceProto = _reflection.GeneratedProtocolMessageType('NamespaceProto', (_message.Message,), {

  'PropertiesEntry' : _reflection.GeneratedProtocolMessageType('PropertiesEntry', (_message.Message,), {
    'DESCRIPTOR' : _NAMESPACEPROTO_PROPERTIESENTRY,
    '__module__' : 'namespace_pb2'
    # @@protoc_insertion_point(class_scope:ai_flow.NamespaceProto.PropertiesEntry)
    })
  ,
  'DESCRIPTOR' : _NAMESPACEPROTO,
  '__module__' : 'namespace_pb2'
  # @@protoc_insertion_point(class_scope:ai_flow.NamespaceProto)
  })
_sym_db.RegisterMessage(NamespaceProto)
_sym_db.RegisterMessage(NamespaceProto.PropertiesEntry)

NamespaceIdentifier = _reflection.GeneratedProtocolMessageType('NamespaceIdentifier', (_message.Message,), {
  'DESCRIPTOR' : _NAMESPACEIDENTIFIER,
  '__module__' : 'namespace_pb2'
  # @@protoc_insertion_point(class_scope:ai_flow.NamespaceIdentifier)
  })
_sym_db.RegisterMessage(NamespaceIdentifier)

UpdateNamespaceRequest = _reflection.GeneratedProtocolMessageType('UpdateNamespaceRequest', (_message.Message,), {

  'PropertiesEntry' : _reflection.GeneratedProtocolMessageType('PropertiesEntry', (_message.Message,), {
    'DESCRIPTOR' : _UPDATENAMESPACEREQUEST_PROPERTIESENTRY,
    '__module__' : 'namespace_pb2'
    # @@protoc_insertion_point(class_scope:ai_flow.UpdateNamespaceRequest.PropertiesEntry)
    })
  ,
  'DESCRIPTOR' : _UPDATENAMESPACEREQUEST,
  '__module__' : 'namespace_pb2'
  # @@protoc_insertion_point(class_scope:ai_flow.UpdateNamespaceRequest)
  })
_sym_db.RegisterMessage(UpdateNamespaceRequest)
_sym_db.RegisterMessage(UpdateNamespaceRequest.PropertiesEntry)


DESCRIPTOR._options = None
_NAMESPACEPROTO_PROPERTIESENTRY._options = None
_UPDATENAMESPACEREQUEST_PROPERTIESENTRY._options = None

_NAMESPACESERVICE = _descriptor.ServiceDescriptor(
  name='NamespaceService',
  full_name='ai_flow.NamespaceService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=416,
  serialized_end=898,
  methods=[
  _descriptor.MethodDescriptor(
    name='addNamespace',
    full_name='ai_flow.NamespaceService.addNamespace',
    index=0,
    containing_service=None,
    input_type=_NAMESPACEPROTO,
    output_type=common__pb2._RESPONSE,
    serialized_options=b'\202\323\344\223\002\023\"\016/namespace/add:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getNamespace',
    full_name='ai_flow.NamespaceService.getNamespace',
    index=1,
    containing_service=None,
    input_type=_NAMESPACEIDENTIFIER,
    output_type=common__pb2._RESPONSE,
    serialized_options=b'\202\323\344\223\002\027\022\025/namespace/get/{name}',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='updateNamespace',
    full_name='ai_flow.NamespaceService.updateNamespace',
    index=2,
    containing_service=None,
    input_type=_UPDATENAMESPACEREQUEST,
    output_type=common__pb2._RESPONSE,
    serialized_options=b'\202\323\344\223\002\026\"\021/namespace/update:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='listNamespace',
    full_name='ai_flow.NamespaceService.listNamespace',
    index=3,
    containing_service=None,
    input_type=common__pb2._LISTREQUEST,
    output_type=common__pb2._RESPONSE,
    serialized_options=b'\202\323\344\223\002\024\"\017/namespace/list:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='deleteNamespace',
    full_name='ai_flow.NamespaceService.deleteNamespace',
    index=4,
    containing_service=None,
    input_type=common__pb2._NAMEREQUEST,
    output_type=common__pb2._RESPONSE,
    serialized_options=b'\202\323\344\223\002\032\022\030/namespace/delete/{name}',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NAMESPACESERVICE)

DESCRIPTOR.services_by_name['NamespaceService'] = _NAMESPACESERVICE

NamespaceService = service_reflection.GeneratedServiceType('NamespaceService', (_service.Service,), dict(
  DESCRIPTOR = _NAMESPACESERVICE,
  __module__ = 'namespace_pb2'
  ))

NamespaceService_Stub = service_reflection.GeneratedServiceStubType('NamespaceService_Stub', (NamespaceService,), dict(
  DESCRIPTOR = _NAMESPACESERVICE,
  __module__ = 'namespace_pb2'
  ))


# @@protoc_insertion_point(module_scope)
