#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workflow.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='workflow.proto',
  package='ai_flow',
  syntax='proto3',
  serialized_options=b'Z\010/ai_flow\220\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eworkflow.proto\x12\x07\x61i_flow\x1a\x1cgoogle/api/annotations.proto\x1a\x0c\x63ommon.proto\"A\n\rWorkflowProto\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tnamespace\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\">\n\x12WorkflowIdentifier\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x15\n\rworkflow_name\x18\x02 \x01(\t\"L\n\x14ListWorkflowsRequest\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x11\n\tpage_size\x18\x02 \x01(\x03\x12\x0e\n\x06offset\x18\x03 \x01(\x03\"R\n\x15UpdateWorkflowRequest\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x15\n\rworkflow_name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t2\x9d\x05\n\x0fWorkflowService\x12R\n\x0b\x61\x64\x64Workflow\x12\x16.ai_flow.WorkflowProto\x1a\x11.ai_flow.Response\"\x18\x82\xd3\xe4\x93\x02\x12\"\r/workflow/add:\x01*\x12`\n\x0eupdateWorkflow\x12\x1e.ai_flow.UpdateWorkflowRequest\x1a\x11.ai_flow.Response\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x10/workflow/update:\x01*\x12W\n\x0bgetWorkflow\x12\x1b.ai_flow.WorkflowIdentifier\x1a\x11.ai_flow.Response\"\x18\x82\xd3\xe4\x93\x02\x12\"\r/workflow/get:\x01*\x12]\n\x0e\x64\x65leteWorkflow\x12\x1b.ai_flow.WorkflowIdentifier\x1a\x11.ai_flow.Response\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x10/workflow/delete:\x01*\x12_\n\x0f\x64isableWorkflow\x12\x1b.ai_flow.WorkflowIdentifier\x1a\x11.ai_flow.Response\"\x1c\x82\xd3\xe4\x93\x02\x16\"\x11/workflow/disable:\x01*\x12]\n\x0e\x65nableWorkflow\x12\x1b.ai_flow.WorkflowIdentifier\x1a\x11.ai_flow.Response\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x10/workflow/enable:\x01*\x12\\\n\rlistWorkflows\x12\x1d.ai_flow.ListWorkflowsRequest\x1a\x11.ai_flow.Response\"\x19\x82\xd3\xe4\x93\x02\x13\"\x0e/workflow/list:\x01*B\rZ\x08/ai_flow\x90\x01\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,common__pb2.DESCRIPTOR,])




_WORKFLOWPROTO = _descriptor.Descriptor(
  name='WorkflowProto',
  full_name='ai_flow.WorkflowProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ai_flow.WorkflowProto.name', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='namespace', full_name='ai_flow.WorkflowProto.namespace', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='ai_flow.WorkflowProto.content', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=136,
)


_WORKFLOWIDENTIFIER = _descriptor.Descriptor(
  name='WorkflowIdentifier',
  full_name='ai_flow.WorkflowIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace', full_name='ai_flow.WorkflowIdentifier.namespace', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='workflow_name', full_name='ai_flow.WorkflowIdentifier.workflow_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=200,
)


_LISTWORKFLOWSREQUEST = _descriptor.Descriptor(
  name='ListWorkflowsRequest',
  full_name='ai_flow.ListWorkflowsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace', full_name='ai_flow.ListWorkflowsRequest.namespace', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='ai_flow.ListWorkflowsRequest.page_size', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='offset', full_name='ai_flow.ListWorkflowsRequest.offset', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=278,
)


_UPDATEWORKFLOWREQUEST = _descriptor.Descriptor(
  name='UpdateWorkflowRequest',
  full_name='ai_flow.UpdateWorkflowRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace', full_name='ai_flow.UpdateWorkflowRequest.namespace', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='workflow_name', full_name='ai_flow.UpdateWorkflowRequest.workflow_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='ai_flow.UpdateWorkflowRequest.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=362,
)

DESCRIPTOR.message_types_by_name['WorkflowProto'] = _WORKFLOWPROTO
DESCRIPTOR.message_types_by_name['WorkflowIdentifier'] = _WORKFLOWIDENTIFIER
DESCRIPTOR.message_types_by_name['ListWorkflowsRequest'] = _LISTWORKFLOWSREQUEST
DESCRIPTOR.message_types_by_name['UpdateWorkflowRequest'] = _UPDATEWORKFLOWREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorkflowProto = _reflection.GeneratedProtocolMessageType('WorkflowProto', (_message.Message,), {
  'DESCRIPTOR' : _WORKFLOWPROTO,
  '__module__' : 'workflow_pb2'
  # @@protoc_insertion_point(class_scope:ai_flow.WorkflowProto)
  })
_sym_db.RegisterMessage(WorkflowProto)

WorkflowIdentifier = _reflection.GeneratedProtocolMessageType('WorkflowIdentifier', (_message.Message,), {
  'DESCRIPTOR' : _WORKFLOWIDENTIFIER,
  '__module__' : 'workflow_pb2'
  # @@protoc_insertion_point(class_scope:ai_flow.WorkflowIdentifier)
  })
_sym_db.RegisterMessage(WorkflowIdentifier)

ListWorkflowsRequest = _reflection.GeneratedProtocolMessageType('ListWorkflowsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTWORKFLOWSREQUEST,
  '__module__' : 'workflow_pb2'
  # @@protoc_insertion_point(class_scope:ai_flow.ListWorkflowsRequest)
  })
_sym_db.RegisterMessage(ListWorkflowsRequest)

UpdateWorkflowRequest = _reflection.GeneratedProtocolMessageType('UpdateWorkflowRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEWORKFLOWREQUEST,
  '__module__' : 'workflow_pb2'
  # @@protoc_insertion_point(class_scope:ai_flow.UpdateWorkflowRequest)
  })
_sym_db.RegisterMessage(UpdateWorkflowRequest)


DESCRIPTOR._options = None

_WORKFLOWSERVICE = _descriptor.ServiceDescriptor(
  name='WorkflowService',
  full_name='ai_flow.WorkflowService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=365,
  serialized_end=1034,
  methods=[
  _descriptor.MethodDescriptor(
    name='addWorkflow',
    full_name='ai_flow.WorkflowService.addWorkflow',
    index=0,
    containing_service=None,
    input_type=_WORKFLOWPROTO,
    output_type=common__pb2._RESPONSE,
    serialized_options=b'\202\323\344\223\002\022\"\r/workflow/add:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='updateWorkflow',
    full_name='ai_flow.WorkflowService.updateWorkflow',
    index=1,
    containing_service=None,
    input_type=_UPDATEWORKFLOWREQUEST,
    output_type=common__pb2._RESPONSE,
    serialized_options=b'\202\323\344\223\002\025\"\020/workflow/update:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getWorkflow',
    full_name='ai_flow.WorkflowService.getWorkflow',
    index=2,
    containing_service=None,
    input_type=_WORKFLOWIDENTIFIER,
    output_type=common__pb2._RESPONSE,
    serialized_options=b'\202\323\344\223\002\022\"\r/workflow/get:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='deleteWorkflow',
    full_name='ai_flow.WorkflowService.deleteWorkflow',
    index=3,
    containing_service=None,
    input_type=_WORKFLOWIDENTIFIER,
    output_type=common__pb2._RESPONSE,
    serialized_options=b'\202\323\344\223\002\025\"\020/workflow/delete:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='disableWorkflow',
    full_name='ai_flow.WorkflowService.disableWorkflow',
    index=4,
    containing_service=None,
    input_type=_WORKFLOWIDENTIFIER,
    output_type=common__pb2._RESPONSE,
    serialized_options=b'\202\323\344\223\002\026\"\021/workflow/disable:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='enableWorkflow',
    full_name='ai_flow.WorkflowService.enableWorkflow',
    index=5,
    containing_service=None,
    input_type=_WORKFLOWIDENTIFIER,
    output_type=common__pb2._RESPONSE,
    serialized_options=b'\202\323\344\223\002\025\"\020/workflow/enable:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='listWorkflows',
    full_name='ai_flow.WorkflowService.listWorkflows',
    index=6,
    containing_service=None,
    input_type=_LISTWORKFLOWSREQUEST,
    output_type=common__pb2._RESPONSE,
    serialized_options=b'\202\323\344\223\002\023\"\016/workflow/list:\001*',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORKFLOWSERVICE)

DESCRIPTOR.services_by_name['WorkflowService'] = _WORKFLOWSERVICE

WorkflowService = service_reflection.GeneratedServiceType('WorkflowService', (_service.Service,), dict(
  DESCRIPTOR = _WORKFLOWSERVICE,
  __module__ = 'workflow_pb2'
  ))

WorkflowService_Stub = service_reflection.GeneratedServiceStubType('WorkflowService_Stub', (WorkflowService,), dict(
  DESCRIPTOR = _WORKFLOWSERVICE,
  __module__ = 'workflow_pb2'
  ))


# @@protoc_insertion_point(module_scope)
